### ISSUE TITLE
How to update/add new panel?

### ISSUE THREAD

**Issue by ShadowPerson** [rix0rrr/sailor#1]
I love sailor! I am very new to doing this sort of interface, and sailor allows me to make the ui with ease. That is, until I tried to make another panel and display it.

If I have `panel1` with a button that calls the function `display_second_panel()` where `panel2` is created, how to I then display `panel2`? I tried `sailor.walk(panel2)`, but then when I exit `panel2`, I return to `panel1` in a non-responsive state(arrow keys no longer work, the only way to exit is to Cntr+C). How would I add this second panel or at least modify the contents of the first panel?

**Comment by rix0rrr** [comment]
Interesting. Can you show me some code that doesn't do what you want?

I have to page this in from wayback, but we should be able to figure this out.

**Comment by ShadowPerson** [comment]
Here is the code that I was experimenting. When I press enter on the first panel's exit button for the first time, I exit properly. However, once I jump to another panel(be it from first to second, or second back to first), when I press enter on the exit button now, it goes back to the panel I was previously on and no longer allows me use the arrow keys. When this happens, the only way to exit is to press Ctrl+C.
```
import sailor


def do_exit(app):
    app.exit = True
    # exit()    <--- If I put this line here, it works as I expect it to, but I
    #                highly doubt this is the right way to do it, and I worry that
    #                if I do this while also managing other resources, such as opened
    #                files, those resources won't be dismantled properly.

def display_second_panel(app):
    panel = sailor.Panel(caption=sailor.Text("Hi - Second Panel"), controls=[
        sailor.Labeled("Hello World 2", sailor.Text("Hi 2")),
        sailor.Labeled("", sailor.Button("Exit", on_click=do_exit))
    ])
    sailor.walk(panel)


def main():
    panel = sailor.Panel(caption=sailor.Text("Hi"), controls=[
        sailor.Labeled("Hello World", sailor.Text("Hi")),
        sailor.Labeled("Second Panel", sailor.Button("Open", on_click=display_second_panel)),
        sailor.Labeled("", sailor.Button("Exit", on_click=do_exit))
    ])
    sailor.walk(panel)


if __name__ == '__main__':
    main()
```

**Comment by rix0rrr** [comment]
Okay, I think I see what's going on. You're really only supposed to do `sailor.walk()` once, to start your app, and it runs until exited.

What you seem to need here is a `Control` that changes its contents between the two screens. From looking at the code, there doesn't seem to be an implementation of that yet.

Also, looking at the code I wrote three years ago... I'm ashamed at the lack of comments 😨 

Let me see if I can throw something together for you

**Comment by rix0rrr** [comment]
This will do it for ya:

```python
import sailor


class SwitchableControl(sailor.Control):
    """A control that can change the control it's displaying."""
    def __init__(self, initial_control, **kwargs):
        super(SwitchableControl, self).__init__(**kwargs)
        self.controls.append(initial_control)

    def switch(self, control):
        self.controls[:] = [control]
        control.enter_focus('', self.app)

    def render(self, app):
        # Nasty hack to hold onto the app object so we can use
        # it in switch() to call enter_focus(). Could have made
        # 'app' a required argument but that seems bad API design.
        self.app = app
        return self.controls[0].render(app)


class MyApp(object):
    """Object with application controls.

    This object makes it convenient to share the single SwitchableControl object
    that we now have between the initialization and the 'display_second_panel'
    event handler. Without putting it on a class, it would have to be a global
    or we'd have to uncomfortably pass it around captured in lambdas.

    Note that although this thing is called 'App', it doesn't have anything to
    do with the 'app' object that is passed to event handlers. Which was a silly
    design decision that I'm regretting. Oh well.
    """
    def __init__(self):
        self.panel1 = sailor.Panel(caption=sailor.Text("Hi"), controls=[
            sailor.Labeled("Hello World", sailor.Text("Hi")),
            sailor.Labeled("Second Panel", sailor.Button("Open", on_click=self.display_second_panel)),
            sailor.Labeled("", sailor.Button("Exit", on_click=self.do_exit))
        ])

        self.panel2 = sailor.Panel(caption=sailor.Text("Hi - Second Panel"), controls=[
            sailor.Labeled("Hello World 2", sailor.Text("Hi 2")),
            sailor.Labeled("First Panel", sailor.Button("Return", on_click=self.do_return)),
            sailor.Labeled("", sailor.Button("Exit", on_click=self.do_exit))
        ])

        self.switchable = SwitchableControl(self.panel1)

    def run(self):
        sailor.walk(self.switchable)

    def display_second_panel(self, _):
        self.switchable.switch(self.panel2)

    def do_return(self, _):
        self.switchable.switch(self.panel1)

    def do_exit(self, app):
        app.exit = True


def main():
    app = MyApp()
    app.run()


if __name__ == '__main__':
    main()
```

**Comment by ShadowPerson** [comment]
I see, that makes sense. Although this gets the job done, I think it can be done better. Not to blame 3-year-ago you, but I think it's the API's responsibility to support a changing control, so creating another Control class outside of sailor.py seems inefficient. I was able to figure something out that wan't too long or complicated, but it's still not the best. It works by totally closing the app and then opening another one with a different panel, which still seems inefficient. 

I like your solution better. I think that, if you're okay with modifying sailor again, the solution you recommended could be a built in part of your code.

```python
import sailor


class MyGUI(object):
    def __init__(self):
        self.exit = False

        self.panel1 = sailor.Panel(caption=sailor.Text("Hi"), controls=[
            sailor.Labeled("Hello World", sailor.Text("Hi")),
            sailor.Labeled("Second Panel",
                           sailor.Button("Open", on_click=lambda app: self.display_panel(app, self.panel2))),
            sailor.Labeled("", sailor.Button("Exit", on_click=self.do_exit))
        ])

        self.panel2 = sailor.Panel(caption=sailor.Text("Hi - Second Panel"), controls=[
            sailor.Labeled("Hello World 2", sailor.Text("Hi 2")),
            sailor.Labeled("First Panel",
                           sailor.Button("Return", on_click=lambda app: self.display_panel(app, self.panel1))),
            sailor.Labeled("", sailor.Button("Exit", on_click=self.do_exit))
        ])

        self.current_panel = self.panel1

    def display_panel(self, app, panel):
        self.current_panel = panel
        app.exit = True

    def run(self):
        while not self.exit:
            sailor.walk(self.current_panel)

    def do_exit(self, app):
        app.exit = True
        self.exit = True


def main():
    my_gui = MyGUI()
    my_gui.run()


if __name__ == '__main__':
    main()
```

**Comment by rix0rrr** [comment]
Oh yeah, I totally agree this particular Control should be a built-in, and I'm totally in favor of adding it to the library proper (in addition to copious docstrings). Will do it when I can find the time.

In the mean time though, until the library is updated, being able to add your own `Control`s outside the library if you can't find the ones that you need built-in is a feature and one that you can take advantage of to unblock yourself.

**Comment by ShadowPerson** [comment]
Sounds good. Thanks for the help!
